import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cpSync, existsSync, readFileSync } from "fs";
import { resolve } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

function getVaultPluginPaths() {
	const configPath = resolve(".devconfig.json");
	if (!existsSync(configPath)) return [];
	try {
		const config = JSON.parse(readFileSync(configPath, "utf-8"));
		if (Array.isArray(config.vaultPluginPaths)) {
			return config.vaultPluginPaths;
		}
		if (typeof config.vaultPluginPath === "string") {
			return [config.vaultPluginPath];
		}
		return [];
	} catch {
		return [];
	}
}

function copyToVault() {
	const vaultPaths = getVaultPluginPaths();
	if (vaultPaths.length === 0) {
		console.log("[copy] 未配置 .devconfig.json 中的 vaultPluginPaths，跳过自动复制");
		console.log("[copy] 如需自动复制，请创建 .devconfig.json: { \"vaultPluginPaths\": [\"你的插件文件夹路径\"] }");
		return;
	}
	const files = ["main.js", "manifest.json", "styles.css"];
	for (const vaultPath of vaultPaths) {
		for (const file of files) {
			try {
				cpSync(resolve(".", file), resolve(vaultPath, file));
				console.log(`[copy] ${file} -> ${vaultPath}`);
			} catch (e) {
				console.log(`[copy] 跳过 ${file} -> ${vaultPath}: ${e.message}`);
			}
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	copyToVault();
	process.exit(0);
} else {
	await context.watch();
}
