/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianAutoCardLink
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");

// src/locale/en.ts
var en = {
  "Enhance default paste": "Enhance default paste",
  "Enhance default paste desc": "Fetch the link metadata when pasting a url in the editor with the default paste command",
  "Show in menu item": "Show in menu item",
  "Show in menu item desc": "Whether to add commands in right click menu items",
  "Follow color scheme": "Follow color scheme",
  "Follow color scheme desc": "Card follows system day/night mode (disable to always use light mode)",
  "Debug mode": "Debug mode",
  "Debug mode desc": "Output detailed parsing logs to the developer console (requires reload)",
  "Cache enabled": "Enable cache",
  "Cache enabled desc": "Cache fetched metadata to avoid re-fetching the same URL",
  "Cache expiry": "Cache expiry (hours)",
  "Cache expiry desc": "How long to keep cached metadata (in hours)",
  "Clear cache": "Clear cache",
  "Clear cache desc": "Clear all cached link metadata",
  "Clear": "Clear",
  "Cache cleared": "Cache cleared",
  "Fallback API": "Fallback metadata API",
  "Fallback API desc": "Use third-party API (Microlink) when direct fetch fails",
  "GitHub card image": "GitHub card image",
  "GitHub card image desc": "Use repository social card as image (slower on first load). Disable to use owner avatar instead.",
  "Reset settings": "Reset settings",
  "Reset settings desc": "Restore all settings to default values",
  "Reset": "Reset",
  "Settings reset": "Settings have been reset",
  "URL pattern": "URL regex pattern",
  "URL pattern desc": "Regex pattern to match for this template",
  "API URL": "API URL",
  "API URL desc": "Official API endpoint (leave empty to skip API)",
  "HTML proxy URL": "HTML proxy URL",
  "HTML proxy desc": "Requires a nitter instance for X/Twitter.",
  "Nitter doc link": "Nitter deployment guide",
  "Test": "Test",
  "Extract config": "Extract Configuration",
  "Bilibili video config": "Bilibili Video Config",
  "X/Twitter config": "X/Twitter Config (requires nitter)",
  "Default link config": "Default Link Config",
  "Field mapping": "Field Mapping",
  "Field mapping desc": "Define fields to extract, one per line. Use field(source) to map from source path",
  "Paste URL and enhance": "Paste URL and enhance to card link",
  "Render as card": "Render as card",
  "Paste and enhance menu": "Paste URL and enhance to card link",
  "Render as card menu": "Render as card",
  "Failed to fetch": "Failed to fetch link metadata",
  "URL copied": "URL copied to clipboard",
  "API URL required": "Please configure API URL first",
  "API request failed": "API request failed",
  "HTML request failed": "HTML request failed",
  "Request error": "Request error",
  "Test result": "Test Result",
  "Copy": "Copy",
  "Copied": "Copied",
  "Close": "Close",
  "YAML parse error": "Failed to parse YAML. Check debug console for more detail.",
  "Required params missing": "Required params [url, title] are not found.",
  "Internal links error": "Internal links must be surrounded by quotes.",
  "Cardlink unknown error": "Code Block: cardlink unknown error",
  "Fetching data": "Fetching Data"
};
var en_default = en;

// src/locale/zh-cn.ts
var zhCN = {
  "Enhance default paste": "\u7C98\u8D34 URL \u4E3A\u5361\u7247",
  "Enhance default paste desc": "\u4F7F\u7528\u9ED8\u8BA4\u7C98\u8D34\u547D\u4EE4\u5728\u7F16\u8F91\u5668\u4E2D\u7C98\u8D34 url \u65F6\u83B7\u53D6\u94FE\u63A5\u5143\u6570\u636E",
  "Show in menu item": "\u53F3\u952E\u83DC\u5355\u547D\u4EE4",
  "Show in menu item desc": "\u662F\u5426\u5728\u53F3\u952E\u83DC\u5355\u4E2D\u6DFB\u52A0\u547D\u4EE4",
  "Follow color scheme": "\u8DDF\u968F\u65E5\u591C\u6A21\u5F0F",
  "Follow color scheme desc": "\u5361\u7247\u662F\u5426\u8DDF\u968F\u7CFB\u7EDF\u65E5\u591C\u6A21\u5F0F\u53D8\u5316\u989C\u8272\uFF08\u5173\u95ED\u5219\u59CB\u7EC8\u4F7F\u7528\u6D45\u8272\u6A21\u5F0F\uFF09",
  "Debug mode": "\u8C03\u8BD5\u6A21\u5F0F",
  "Debug mode desc": "\u5728\u5F00\u53D1\u8005\u63A7\u5236\u53F0\u8F93\u51FA\u8BE6\u7EC6\u89E3\u6790\u65E5\u5FD7\uFF08\u9700\u8981\u91CD\u65B0\u52A0\u8F7D\uFF09",
  "Cache enabled": "\u542F\u7528\u7F13\u5B58",
  "Cache enabled desc": "\u7F13\u5B58\u5DF2\u83B7\u53D6\u7684\u5143\u6570\u636E\uFF0C\u907F\u514D\u91CD\u590D\u8BF7\u6C42\u76F8\u540C URL",
  "Cache expiry": "\u7F13\u5B58\u8FC7\u671F\u65F6\u95F4\uFF08\u5C0F\u65F6\uFF09",
  "Cache expiry desc": "\u7F13\u5B58\u5143\u6570\u636E\u7684\u4FDD\u7559\u65F6\u957F\uFF08\u5355\u4F4D\uFF1A\u5C0F\u65F6\uFF09",
  "Clear cache": "\u6E05\u9664\u7F13\u5B58",
  "Clear cache desc": "\u6E05\u9664\u6240\u6709\u5DF2\u7F13\u5B58\u7684\u94FE\u63A5\u5143\u6570\u636E",
  "Clear": "\u6E05\u9664",
  "Cache cleared": "\u7F13\u5B58\u5DF2\u6E05\u9664",
  "Fallback API": "\u5907\u7528\u5143\u6570\u636E API",
  "Fallback API desc": "\u76F4\u63A5\u8BF7\u6C42\u5931\u8D25\u65F6\u4F7F\u7528\u7B2C\u4E09\u65B9 API\uFF08Microlink\uFF09\u83B7\u53D6\u5143\u6570\u636E",
  "GitHub card image": "GitHub \u5361\u7247\u56FE\u7247",
  "GitHub card image desc": "\u4F7F\u7528\u4ED3\u5E93\u793E\u4EA4\u5361\u7247\u4F5C\u4E3A\u56FE\u7247\uFF08\u9996\u6B21\u83B7\u53D6\u8F83\u6162\uFF09\u3002\u5173\u95ED\u5219\u4F7F\u7528\u4F5C\u8005\u5934\u50CF\u3002",
  "Reset settings": "\u91CD\u7F6E\u914D\u7F6E",
  "Reset settings desc": "\u5C06\u6240\u6709\u914D\u7F6E\u6062\u590D\u4E3A\u9ED8\u8BA4\u503C",
  "Reset": "\u91CD\u7F6E",
  "Settings reset": "\u914D\u7F6E\u5DF2\u91CD\u7F6E",
  "URL pattern": "URL \u6B63\u5219\u5339\u914D",
  "URL pattern desc": "\u5339\u914D\u6B64\u6A21\u677F\u7684\u6B63\u5219\u8868\u8FBE\u5F0F",
  "API URL": "API \u5730\u5740",
  "API URL desc": "\u7F51\u7AD9\u5B98\u65B9\u7ED9\u51FA\u7684 API \u63A5\u53E3\u5730\u5740\uFF08\u7559\u7A7A\u5219\u4E0D\u4F7F\u7528 API\uFF09",
  "HTML proxy URL": "HTML \u4EE3\u7406\u5730\u5740",
  "HTML proxy desc": "\u83B7\u53D6 X/Twitter \u4FE1\u606F\u9700\u8981\u90E8\u7F72 nitter",
  "Nitter doc link": "Nitter \u90E8\u7F72\u6587\u6863",
  "Test": "\u6D4B\u8BD5",
  "Extract config": "\u63D0\u53D6\u914D\u7F6E",
  "Bilibili video config": "B \u7AD9\u89C6\u9891\u914D\u7F6E",
  "X/Twitter config": "X/Twitter \u914D\u7F6E\uFF08\u9700\u8981\u914D\u7F6E nitter\uFF09",
  "Default link config": "\u901A\u7528\u94FE\u63A5\u914D\u7F6E",
  "Field mapping": "\u5B57\u6BB5\u6620\u5C04",
  "Field mapping desc": "\u5B9A\u4E49\u8981\u63D0\u53D6\u7684\u5B57\u6BB5\uFF0C\u6BCF\u884C\u4E00\u4E2A\u3002\u4F7F\u7528 field(source) \u4ECE\u6E90\u8DEF\u5F84\u6620\u5C04",
  "Paste URL and enhance": "\u7C98\u8D34 URL \u4E3A\u5361\u7247",
  "Render as card": "\u6E32\u67D3\u4E3A\u5361\u7247",
  "Paste and enhance menu": "\u7C98\u8D34 URL \u4E3A\u5361\u7247",
  "Render as card menu": "\u6E32\u67D3\u4E3A\u5361\u7247",
  "Failed to fetch": "\u65E0\u6CD5\u83B7\u53D6\u94FE\u63A5\u6570\u636E",
  "URL copied": "URL \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F",
  "API URL required": "\u8BF7\u5148\u914D\u7F6E API \u5730\u5740",
  "API request failed": "API \u8BF7\u6C42\u5931\u8D25",
  "HTML request failed": "HTML \u8BF7\u6C42\u5931\u8D25",
  "Request error": "\u8BF7\u6C42\u9519\u8BEF",
  "Test result": "\u6D4B\u8BD5\u7ED3\u679C",
  "Copy": "\u590D\u5236",
  "Copied": "\u5DF2\u590D\u5236",
  "Close": "\u5173\u95ED",
  "YAML parse error": "YAML \u89E3\u6790\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B\u63A7\u5236\u53F0\u83B7\u53D6\u8BE6\u7EC6\u4FE1\u606F",
  "Required params missing": "\u7F3A\u5C11\u5FC5\u8981\u53C2\u6570 [url, title]",
  "Internal links error": "\u5185\u90E8\u94FE\u63A5\u5FC5\u987B\u7528\u5F15\u53F7\u5305\u56F4",
  "Cardlink unknown error": "\u4EE3\u7801\u5757\uFF1A\u5361\u7247\u94FE\u63A5\u672A\u77E5\u9519\u8BEF",
  "Fetching data": "\u83B7\u53D6\u6570\u636E\u4E2D"
};
var zh_cn_default = zhCN;

// src/i18n.ts
var localeMap = {
  en: en_default,
  "zh-cn": zh_cn_default,
  "zh-CN": zh_cn_default,
  "zh-TW": zh_cn_default,
  "zh-Hans": zh_cn_default,
  "zh-Hant": zh_cn_default
};
var locale = localeMap[import_obsidian.moment.locale()] || en_default;
function t(str) {
  return locale && locale[str] || en_default[str] || str;
}

// src/utils.ts
var DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
var _debugEnabled = false;
function setDebugEnabled(enabled) {
  _debugEnabled = enabled;
}
function log(...args) {
  if (_debugEnabled) {
    console.log("[auto-card-link]", ...args);
  }
}
function logGroupStart(label) {
  if (_debugEnabled) {
    console.groupCollapsed(`[auto-card-link] ${label}`);
  }
}
function logGroupEnd() {
  if (_debugEnabled) {
    console.groupEnd();
  }
}
function formatDateFromTimestamp(timestamp) {
  const date = new Date(timestamp * 1e3);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function formatDateFromString(dateStr) {
  if (!dateStr)
    return void 0;
  try {
    const date = new Date(dateStr);
    if (isNaN(date.getTime()))
      return void 0;
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  } catch (e) {
    return void 0;
  }
}
function formatNumberCN(num) {
  if (num >= 1e8) {
    return (num / 1e8).toFixed(1) + "\u4EBF";
  } else if (num >= 1e4) {
    return (num / 1e4).toFixed(1) + "\u4E07";
  }
  return num.toString();
}
function formatNumberEN(num) {
  if (num >= 1e3) {
    return (num / 1e3).toFixed(1) + "k";
  }
  return num.toString();
}
function sanitizeText(text) {
  return text.replace(/\r\n|\n|\r/g, " ").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
}
function extractCleanImageUrl(url) {
  if (!url)
    return "";
  let cleanUrl = url.trim().split(" ")[0];
  if (cleanUrl.startsWith("//")) {
    cleanUrl = "https:" + cleanUrl;
  }
  const atMatch = cleanUrl.match(/^(https?:\/\/[^\s]+?)@/);
  if (atMatch) {
    return atMatch[1];
  }
  return cleanUrl;
}
function isCoverUrl(url) {
  return /\/new_dyn\//i.test(url);
}
function isAvatarUrl(url) {
  if (/\/bfs\/face\//i.test(url) && !/\/noface/i.test(url))
    return true;
  if (/\/profile_images\//i.test(url))
    return true;
  return false;
}
function extractImagesFromDoc(doc) {
  const result = {};
  const allImgs = doc.querySelectorAll("img[src]");
  const imgList = Array.from(allImgs);
  const imgSrcs = [];
  for (let i = 0; i < imgList.length; i++) {
    const img = imgList[i];
    const src = img.getAttribute("src") || "";
    if (!src || src.startsWith("data:"))
      continue;
    imgSrcs.push(src);
    if (isCoverUrl(src) && !result.cover) {
      result.cover = extractCleanImageUrl(src);
    }
    if (isAvatarUrl(src) && !result.avatar) {
      result.avatar = extractCleanImageUrl(src);
    }
    if (!result.firstImg) {
      result.firstImg = extractCleanImageUrl(src);
    }
    if (result.cover && result.avatar)
      break;
  }
  if (!result.avatar) {
    const appleTouchIcon = doc.querySelector("link[rel='apple-touch-icon']");
    if (appleTouchIcon == null ? void 0 : appleTouchIcon.href) {
      const href = appleTouchIcon.href;
      if (isAvatarUrl(href)) {
        result.avatar = extractCleanImageUrl(href);
        imgSrcs.push(`[apple-touch-icon]${href}`);
      }
    }
  }
  if (!result.firstImg && imgSrcs.length === 0) {
    const linkIcon = doc.querySelector("link[rel='icon'], link[rel='shortcut icon']");
    if (linkIcon == null ? void 0 : linkIcon.href) {
      imgSrcs.push(`[link-icon]${linkIcon.href}`);
    }
  }
  log("extractImagesFromDoc: img src\u5217\u8868:", imgSrcs.length > 0 ? imgSrcs : "\u65E0", "\u7ED3\u679C:", JSON.stringify(result));
  return result;
}
function resolveFirstDefined(...values) {
  for (const v of values) {
    if (v !== void 0 && v !== null) {
      if (typeof v === "string" && v === "")
        continue;
      return v;
    }
  }
  return void 0;
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  enhanceDefaultPaste: true,
  showInMenuItem: true,
  followColorScheme: true,
  cacheEnabled: false,
  cacheExpiry: 24,
  fallbackApiEnabled: true,
  debugEnabled: false,
  githubCardImage: true,
  tpl_x_htmlProxyUrl: "http://127.0.0.1:8080"
};
var ObsidianAutoCardLinkSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Link Card" });
    new import_obsidian2.Setting(containerEl).setName(t("Enhance default paste")).setDesc(t("Enhance default paste desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enhanceDefaultPaste).onChange(async (value) => {
        this.plugin.settings.enhanceDefaultPaste = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Show in menu item")).setDesc(t("Show in menu item desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showInMenuItem).onChange(async (value) => {
        this.plugin.settings.showInMenuItem = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Follow color scheme")).setDesc(t("Follow color scheme desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.followColorScheme).onChange(async (value) => {
        this.plugin.settings.followColorScheme = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Debug mode")).setDesc(t("Debug mode desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.debugEnabled).onChange(async (value) => {
        this.plugin.settings.debugEnabled = value;
        setDebugEnabled(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Cache enabled")).setDesc(t("Cache enabled desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.cacheEnabled).onChange(async (value) => {
        this.plugin.settings.cacheEnabled = value;
        this.plugin.cache.setEnabled(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Cache expiry")).setDesc(t("Cache expiry desc")).addSlider(
      (slider) => slider.setLimits(1, 168, 1).setValue(this.plugin.settings.cacheExpiry).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.cacheExpiry = value;
        this.plugin.cache.setExpiry(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Clear cache")).setDesc(t("Clear cache desc")).addButton(
      (button) => button.setButtonText(t("Clear")).onClick(async () => {
        this.plugin.cache.clear();
        await this.plugin.saveSettings();
        new import_obsidian2.Notice(t("Cache cleared"));
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("Fallback API")).setDesc(t("Fallback API desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.fallbackApiEnabled).onChange(async (value) => {
        this.plugin.settings.fallbackApiEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("GitHub card image")).setDesc(t("GitHub card image desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.githubCardImage).onChange(async (value) => {
        this.plugin.settings.githubCardImage = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("X/Twitter proxy URL").setDesc(t("HTML proxy desc")).addText(
      (text) => text.setPlaceholder("http://127.0.0.1:8080").setValue(this.plugin.settings.tpl_x_htmlProxyUrl).onChange(async (value) => {
        this.plugin.settings.tpl_x_htmlProxyUrl = value;
        await this.plugin.saveSettings();
      })
    );
    const nitterDocUrl = import_obsidian2.moment.locale().startsWith("zh") ? "https://github.com/Hsyoungtick/twitter-gallery/blob/main/docs/nitter_config_zh.md" : "https://github.com/Hsyoungtick/twitter-gallery/blob/main/docs/nitter_config.md";
    (_a = containerEl.querySelector(".setting-item:last-child .setting-item-description")) == null ? void 0 : _a.createEl("a", {
      href: nitterDocUrl,
      text: t("Nitter doc link"),
      attr: { target: "_blank" }
    });
    new import_obsidian2.Setting(containerEl).setName(t("Reset settings")).setDesc(t("Reset settings desc")).addButton(
      (button) => button.setButtonText(t("Reset")).onClick(async () => {
        Object.assign(this.plugin.settings, DEFAULT_SETTINGS);
        setDebugEnabled(DEFAULT_SETTINGS.debugEnabled);
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian2.Notice(t("Settings reset"));
      })
    );
  }
};

// src/code_block_generator.ts
var import_obsidian7 = require("obsidian");

// src/regex.ts
var urlRegex = /^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})$/i;
var lineRegex = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
var linkRegex = /^\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)$/i;
var linkLineRegex = /\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)/gi;
var imageRegex = /\.(gif|jpe?g|tiff?|png|webp|bmp|tga|psd|ai)$/i;

// src/editor_enhancements.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const wordBoundaries = this.getWordBoundaries(editor);
      editor.setSelection(wordBoundaries.start, wordBoundaries.end);
    }
    return editor.getSelection();
  }
  static isCursorWithinBoundaries(cursor, match) {
    var _a;
    const startIndex = (_a = match.index) != null ? _a : 0;
    const endIndex = startIndex + match[0].length;
    return startIndex <= cursor.ch && cursor.ch <= endIndex;
  }
  static getWordBoundaries(editor) {
    var _a, _b;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    const linksInLine = lineText.matchAll(linkLineRegex);
    for (const match of linksInLine) {
      if (this.isCursorWithinBoundaries(cursor, match)) {
        const startCh = (_a = match.index) != null ? _a : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    const urlsInLine = lineText.matchAll(lineRegex);
    for (const match of urlsInLine) {
      if (this.isCursorWithinBoundaries(cursor, match)) {
        const startCh = (_b = match.index) != null ? _b : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    return { start: cursor, end: cursor };
  }
  static getEditorPositionFromIndex(content, index) {
    const substr = content.substr(0, index);
    let l = 0;
    let offset = -1;
    let r = -1;
    for (; (r = substr.indexOf("\n", r + 1)) !== -1; l++, offset = r)
      ;
    offset += 1;
    const ch = content.substr(offset, index - offset).length;
    return { line: l, ch };
  }
};

// src/bilibili_parser.ts
var import_obsidian3 = require("obsidian");
var BilibiliParser = class {
  constructor(url, apiUrl = "https://api.bilibili.com/x/web-interface/view") {
    this.url = url;
    this.apiUrl = apiUrl;
  }
  static isBilibiliUrl(url) {
    try {
      const hostname = new URL(url).hostname;
      return hostname === "bilibili.com" || hostname === "www.bilibili.com" || hostname.endsWith(".bilibili.com");
    } catch (e) {
      return false;
    }
  }
  static extractVideoId(url) {
    const bvMatch = url.match(/\/video\/(BV[a-zA-Z0-9]+)/i);
    if (bvMatch)
      return { type: "bvid", id: bvMatch[1] };
    const avMatch = url.match(/\/video\/av(\d+)/i);
    if (avMatch)
      return { type: "avid", id: avMatch[1] };
    return null;
  }
  async parse() {
    const videoId = BilibiliParser.extractVideoId(this.url);
    if (videoId) {
      return await this.parseVideo(videoId);
    }
    return await this.parseOpusFromHTML();
  }
  async parseVideo(videoId) {
    var _a, _b, _c, _d;
    try {
      const apiUrl = videoId.type === "bvid" ? `${this.apiUrl}?bvid=${videoId.id}` : `${this.apiUrl}?aid=${videoId.id}`;
      const res = await (0, import_obsidian3.requestUrl)({
        url: apiUrl,
        headers: {
          "User-Agent": DEFAULT_USER_AGENT,
          Referer: "https://www.bilibili.com/",
          Origin: "https://www.bilibili.com",
          Cookie: `buvid3=${this.generateBuvid3()}`
        }
      });
      if (res.status !== 200 || !res.json || res.json.code !== 0) {
        log("Bilibili API \u8FD4\u56DE\u9519\u8BEF: status=", res.status, "code=", (_a = res.json) == null ? void 0 : _a.code);
        return null;
      }
      const data = res.json.data;
      log("Bilibili API \u539F\u59CB\u6570\u636E: pubdate=", data.pubdate, "ctime=", data.ctime, "duration=", data.duration, "view=", (_b = data.stat) == null ? void 0 : _b.view);
      const title = sanitizeText(data.title);
      const coverUrl = extractCleanImageUrl(data.pic);
      const avatarUrl = ((_c = data.owner) == null ? void 0 : _c.face) ? extractCleanImageUrl(data.owner.face) : void 0;
      const imageCandidates = [
        { source: "cover(pic)", value: coverUrl },
        { source: "avatar(owner.face)", value: avatarUrl }
      ];
      const selectedImage = coverUrl || avatarUrl || void 0;
      const selectedSource = coverUrl ? "cover(pic)" : avatarUrl ? "avatar(owner.face)" : "\u65E0";
      log("Bilibili parse: \u56FE\u7247\u56DE\u9000\u94FE:", imageCandidates.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "), `\u2192 \u6700\u7EC8\u9009\u62E9${selectedSource}\u4F5C\u4E3Aimage`);
      const pubdate = data.pubdate ? formatDateFromTimestamp(data.pubdate) : void 0;
      const updated_at = data.ctime ? formatDateFromTimestamp(data.ctime) : void 0;
      const date = pubdate || updated_at;
      log("Bilibili parse: \u65E5\u671F\u56DE\u9000\u94FE: pubdate(" + (data.pubdate || "\u65E0") + ") -> ctime(" + (data.ctime || "\u65E0") + ") \u2192 \u6700\u7EC8\u9009\u62E9date=" + (date || "\u65E0"));
      const result = {
        url: this.url,
        title,
        host: "bilibili.com",
        image: selectedImage,
        avatar: avatarUrl || void 0,
        author: (_d = data.owner) == null ? void 0 : _d.name,
        duration: this.formatDuration(data.duration),
        views: formatNumberCN(data.stat.view),
        date,
        indent: 0
      };
      log("Bilibili parse: \u6700\u7EC8\u5B57\u6BB5 title=", result.title, "author=", result.author || "\u65E0", "views=", result.views || "\u65E0", "date=", result.date || "\u65E0", "duration=", result.duration || "\u65E0");
      return result;
    } catch (e) {
      log("Bilibili API error:", e);
      return null;
    }
  }
  async parseOpusFromHTML() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    try {
      const buvid3 = this.generateBuvid3();
      const res = await (0, import_obsidian3.requestUrl)({
        url: this.url,
        headers: {
          "User-Agent": DEFAULT_USER_AGENT,
          Referer: "https://www.bilibili.com/",
          Origin: "https://www.bilibili.com",
          Cookie: `buvid3=${buvid3}`
        }
      });
      if (res.status !== 200)
        return null;
      const html = res.text;
      let title = "";
      let authorName = "";
      let pubTs = 0;
      let ogImage = "";
      let avatar = "";
      const initMatch = html.match(
        /window\.__INITIAL_STATE__\s*=\s*(\{[\s\S]*?\});/
      );
      if (initMatch) {
        try {
          const state = JSON.parse(initMatch[1]);
          const modules = ((_a = state.detail) == null ? void 0 : _a.modules) || {};
          log("Bilibili opus __INITIAL_STATE__ \u9876\u5C42keys:", Object.keys(state), "detail keys:", state.detail ? Object.keys(state.detail) : "\u65E0");
          for (const [, mod] of Object.entries(modules)) {
            if ((mod == null ? void 0 : mod.module_type) === "MODULE_TYPE_TITLE") {
              title = (((_b = mod.module_title) == null ? void 0 : _b.text) || "").replace(" - \u54D4\u54E9\u54D4\u54E9", "").trim();
            }
            if ((mod == null ? void 0 : mod.module_type) === "MODULE_TYPE_AUTHOR") {
              authorName = ((_c = mod.module_author) == null ? void 0 : _c.name) || "";
              pubTs = ((_d = mod.module_author) == null ? void 0 : _d.pub_ts) || 0;
              const face = ((_e = mod.module_author) == null ? void 0 : _e.face) || ((_f = mod.module_author) == null ? void 0 : _f.avatar_url) || "";
              if (face) {
                avatar = extractCleanImageUrl(face);
              }
              log("Bilibili opus MODULE_TYPE_AUTHOR: name=", authorName, "pub_ts=", pubTs, "face=", face ? "\u6709" : "\u65E0");
            }
            if ((mod == null ? void 0 : mod.module_type) === "MODULE_TYPE_SHARE" || (mod == null ? void 0 : mod.module_type) === "MODULE_TYPE_TITLE_EXTRA") {
              const sharePic = (_g = mod.share_info) == null ? void 0 : _g.pic;
              if (sharePic && !sharePic.includes("app_logo") && !ogImage) {
                ogImage = sharePic;
              }
            }
          }
        } catch (e) {
          log("Failed to parse __INITIAL_STATE__:", e);
        }
      }
      if (!avatar || !authorName) {
        const appleTouchIcon = html.match(/<link[^>]+rel=["']apple-touch-icon["'][^>]+href=["']([^"']+)["']/i);
        if (appleTouchIcon) {
          const iconUrl = appleTouchIcon[1];
          if (/\/bfs\/face\//i.test(iconUrl) && !avatar) {
            avatar = extractCleanImageUrl(iconUrl);
            log("Bilibili opus: \u4ECEapple-touch-icon\u63D0\u53D6avatar:", avatar);
          }
        }
      }
      const parser = new DOMParser();
      const doc = parser.parseFromString(html, "text/html");
      if (!title) {
        const titleEl = doc.querySelector("title");
        title = titleEl ? ((_h = titleEl.textContent) == null ? void 0 : _h.replace(" - \u54D4\u54E9\u54D4\u54E9", "").trim()) || "" : "";
      }
      if (!ogImage) {
        const ogImageEl = doc.querySelector(
          "meta[property='og:image']"
        );
        const ogImageContent = ogImageEl ? ogImageEl.getAttribute("content") || "" : "";
        if (ogImageContent) {
          ogImage = ogImageContent;
        }
      }
      const extractedImages = extractImagesFromDoc(doc);
      if (extractedImages.avatar && !avatar) {
        avatar = extractedImages.avatar;
      }
      title = sanitizeText(title);
      const imageCandidates = [
        { source: "og:image", value: ogImage },
        { source: "cover", value: extractedImages.cover },
        { source: "avatar", value: avatar || extractedImages.avatar },
        { source: "firstImg", value: extractedImages.firstImg }
      ];
      const selectedImage = extractCleanImageUrl(
        ogImage || extractedImages.cover || avatar || extractedImages.avatar || extractedImages.firstImg || ""
      ) || void 0;
      const selectedSource = ogImage ? "og:image" : extractedImages.cover ? "cover" : avatar ? "avatar" : extractedImages.firstImg ? "firstImg" : "\u65E0";
      log("Bilibili opus: \u56FE\u7247\u56DE\u9000\u94FE:", imageCandidates.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "), `\u2192 \u6700\u7EC8\u9009\u62E9${selectedSource}\u4F5C\u4E3Aimage`);
      const pubdate = pubTs ? formatDateFromTimestamp(pubTs) : void 0;
      log("Bilibili opus: \u65E5\u671F\u56DE\u9000\u94FE: pub_ts(" + (pubTs || "\u65E0") + ") \u2192 \u6700\u7EC8\u9009\u62E9date=" + (pubdate || "\u65E0"));
      const result = {
        url: this.url,
        title,
        host: "bilibili.com",
        image: selectedImage,
        avatar: avatar || extractedImages.avatar || void 0,
        author: authorName || void 0,
        date: pubdate,
        indent: 0
      };
      log("Bilibili opus: \u6700\u7EC8\u5B57\u6BB5 title=", result.title, "author=", result.author || "\u65E0", "date=", result.date || "\u65E0");
      return result;
    } catch (e) {
      log("Bilibili opus HTML parse error:", e);
      return null;
    }
  }
  formatDuration(seconds) {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor(seconds % 3600 / 60);
    const s = seconds % 60;
    if (h > 0) {
      return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
    }
    return `${m}:${s.toString().padStart(2, "0")}`;
  }
  generateBuvid3() {
    var _a;
    const chars = "0123456789ABCDEF";
    const mac = Array.from(
      { length: 12 },
      () => chars[Math.floor(Math.random() * chars.length)]
    ).join("");
    const formattedMac = ((_a = mac.match(/.{2}/g)) == null ? void 0 : _a.join(":")) || mac;
    const md5Hash = md5(formattedMac);
    const suffix = md5Hash.substring(0, 8).toUpperCase();
    return `${mac}${suffix}`;
  }
};
function md5(string) {
  function md5cycle(x, k) {
    let a = x[0], b = x[1], c = x[2], d = x[3];
    a = ff(a, b, c, d, k[0], 7, -680876936);
    d = ff(d, a, b, c, k[1], 12, -389564586);
    c = ff(c, d, a, b, k[2], 17, 606105819);
    b = ff(b, c, d, a, k[3], 22, -1044525330);
    a = ff(a, b, c, d, k[4], 7, -176418897);
    d = ff(d, a, b, c, k[5], 12, 1200080426);
    c = ff(c, d, a, b, k[6], 17, -1473231341);
    b = ff(b, c, d, a, k[7], 22, -45705983);
    a = ff(a, b, c, d, k[8], 7, 1770035416);
    d = ff(d, a, b, c, k[9], 12, -1958414417);
    c = ff(c, d, a, b, k[10], 17, -42063);
    b = ff(b, c, d, a, k[11], 22, -1990404162);
    a = ff(a, b, c, d, k[12], 7, 1804603682);
    d = ff(d, a, b, c, k[13], 12, -40341101);
    c = ff(c, d, a, b, k[14], 17, -1502002290);
    b = ff(b, c, d, a, k[15], 22, 1236535329);
    a = gg(a, b, c, d, k[1], 5, -165796510);
    d = gg(d, a, b, c, k[6], 9, -1069501632);
    c = gg(c, d, a, b, k[11], 14, 643717713);
    b = gg(b, c, d, a, k[0], 20, -373897302);
    a = gg(a, b, c, d, k[5], 5, -701558691);
    d = gg(d, a, b, c, k[10], 9, 38016083);
    c = gg(c, d, a, b, k[15], 14, -660478335);
    b = gg(b, c, d, a, k[4], 20, -405537848);
    a = gg(a, b, c, d, k[9], 5, 568446438);
    d = gg(d, a, b, c, k[14], 9, -1019803690);
    c = gg(c, d, a, b, k[3], 14, -187363961);
    b = gg(b, c, d, a, k[8], 20, 1163531501);
    a = gg(a, b, c, d, k[13], 5, -1444681467);
    d = gg(d, a, b, c, k[2], 9, -51403784);
    c = gg(c, d, a, b, k[7], 14, 1735328473);
    b = gg(b, c, d, a, k[12], 20, -1926607734);
    a = hh(a, b, c, d, k[5], 4, -378558);
    d = hh(d, a, b, c, k[8], 11, -2022574463);
    c = hh(c, d, a, b, k[11], 16, 1839030562);
    b = hh(b, c, d, a, k[14], 23, -35309556);
    a = hh(a, b, c, d, k[1], 4, -1530992060);
    d = hh(d, a, b, c, k[4], 11, 1272893353);
    c = hh(c, d, a, b, k[7], 16, -155497632);
    b = hh(b, c, d, a, k[10], 23, -1094730640);
    a = hh(a, b, c, d, k[13], 4, 681279174);
    d = hh(d, a, b, c, k[0], 11, -358537222);
    c = hh(c, d, a, b, k[3], 16, -722521979);
    b = hh(b, c, d, a, k[6], 23, 76029189);
    a = hh(a, b, c, d, k[9], 4, -640364487);
    d = hh(d, a, b, c, k[12], 11, -421815835);
    c = hh(c, d, a, b, k[15], 16, 530742520);
    b = hh(b, c, d, a, k[2], 23, -995338651);
    a = ii(a, b, c, d, k[0], 6, -198630844);
    d = ii(d, a, b, c, k[7], 10, 1126891415);
    c = ii(c, d, a, b, k[14], 15, -1416354905);
    b = ii(b, c, d, a, k[5], 21, -57434055);
    a = ii(a, b, c, d, k[12], 6, 1700485571);
    d = ii(d, a, b, c, k[3], 10, -1894986606);
    c = ii(c, d, a, b, k[10], 15, -1051523);
    b = ii(b, c, d, a, k[1], 21, -2054922799);
    a = ii(a, b, c, d, k[8], 6, 1873313359);
    d = ii(d, a, b, c, k[15], 10, -30611744);
    c = ii(c, d, a, b, k[6], 15, -1560198380);
    b = ii(b, c, d, a, k[13], 21, 1309151649);
    a = ii(a, b, c, d, k[4], 6, -145523070);
    d = ii(d, a, b, c, k[11], 10, -1120210379);
    c = ii(c, d, a, b, k[2], 15, 718787259);
    b = ii(b, c, d, a, k[9], 21, -343485551);
    x[0] = add32(a, x[0]);
    x[1] = add32(b, x[1]);
    x[2] = add32(c, x[2]);
    x[3] = add32(d, x[3]);
  }
  function cmn(q, a, b, x, s, t2) {
    a = add32(add32(a, q), add32(x, t2));
    return add32(a << s | a >>> 32 - s, b);
  }
  function ff(a, b, c, d, x, s, t2) {
    return cmn(b & c | ~b & d, a, b, x, s, t2);
  }
  function gg(a, b, c, d, x, s, t2) {
    return cmn(b & d | c & ~d, a, b, x, s, t2);
  }
  function hh(a, b, c, d, x, s, t2) {
    return cmn(b ^ c ^ d, a, b, x, s, t2);
  }
  function ii(a, b, c, d, x, s, t2) {
    return cmn(c ^ (b | ~d), a, b, x, s, t2);
  }
  function add32(a, b) {
    return a + b & 4294967295;
  }
  function md5blk(s) {
    const md5blks = [];
    for (let i2 = 0; i2 < 64; i2 += 4) {
      md5blks[i2 >> 2] = s.charCodeAt(i2) + (s.charCodeAt(i2 + 1) << 8) + (s.charCodeAt(i2 + 2) << 16) + (s.charCodeAt(i2 + 3) << 24);
    }
    return md5blks;
  }
  const hex_chr = "0123456789abcdef".split("");
  function rhex(n2) {
    let s = "";
    for (let j = 0; j < 4; j++) {
      s += hex_chr[n2 >> j * 8 + 4 & 15] + hex_chr[n2 >> j * 8 & 15];
    }
    return s;
  }
  function hex(x) {
    return x.map(rhex).join("");
  }
  let n = string.length;
  let state = [1732584193, -271733879, -1732584194, 271733878];
  let i;
  for (i = 64; i <= n; i += 64) {
    md5cycle(state, md5blk(string.substring(i - 64, i)));
  }
  string = string.substring(i - 64);
  const tail = new Array(16).fill(0);
  for (i = 0; i < string.length; i++) {
    tail[i >> 2] |= string.charCodeAt(i) << (i % 4 << 3);
  }
  tail[i >> 2] |= 128 << (i % 4 << 3);
  if (i > 55) {
    md5cycle(state, tail);
    for (i = 0; i < 16; i++)
      tail[i] = 0;
  }
  tail[14] = n * 8;
  md5cycle(state, tail);
  return hex(state);
}

// src/github_parser.ts
var import_obsidian4 = require("obsidian");
var GitHubParser = class {
  constructor(url, useCardImage = true) {
    this.url = url;
    this.useCardImage = useCardImage;
  }
  static isGitHubUrl(url) {
    const githubRegex = /^https?:\/\/(www\.)?github\.com\/[^\/]+\/[^\/]+/i;
    return githubRegex.test(url);
  }
  static extractRepoInfo(url) {
    const match = url.match(/github\.com\/([^\/]+)\/([^\/]+)/i);
    if (match) {
      return { owner: match[1], repo: match[2] };
    }
    return null;
  }
  async parse() {
    const repoInfo = GitHubParser.extractRepoInfo(this.url);
    if (!repoInfo)
      return null;
    try {
      return await this.parseFromApi(repoInfo.owner, repoInfo.repo);
    } catch (e) {
      log("GitHub API error, falling back to HTML:", e);
      return await this.parseFromHtml();
    }
  }
  async parseFromApi(owner, repo) {
    var _a, _b, _c, _d;
    try {
      const apiUrl = `https://api.github.com/repos/${owner}/${repo}`;
      const res = await (0, import_obsidian4.requestUrl)({
        url: apiUrl,
        headers: {
          Accept: "application/vnd.github.v3+json",
          "User-Agent": "obsidian-auto-card-link"
        }
      });
      if (res.status !== 200 || !res.json) {
        return await this.parseFromHtml();
      }
      const data = res.json;
      log("GitHub API \u539F\u59CB\u6570\u636E: full_name=", data.full_name, "stargazers_count=", data.stargazers_count, "updated_at=", data.updated_at, "language=", data.language, "owner.login=", (_a = data.owner) == null ? void 0 : _a.login);
      const title = sanitizeText(repo || data.full_name || `${owner}/${repo}`);
      const description = data.description ? sanitizeText(data.description) : void 0;
      let date;
      if (data.created_at) {
        date = formatDateFromString(data.created_at);
      }
      log("GitHub parse: \u65E5\u671F\u56DE\u9000\u94FE: created_at(" + (data.created_at || "\u65E0") + ") \u2192 \u6700\u7EC8\u9009\u62E9date=" + (date || "\u65E0"));
      const coverUrl = this.useCardImage ? `https://opengraph.githubassets.com/1/${owner}/${repo}` : ((_b = data.owner) == null ? void 0 : _b.avatar_url) || void 0;
      const avatarUrl = ((_c = data.owner) == null ? void 0 : _c.avatar_url) || void 0;
      log("GitHub parse: image=" + (this.useCardImage ? "opengraph" : "avatar") + "(" + (coverUrl || "\u65E0") + ")");
      const result = {
        url: this.url,
        title,
        description,
        host: "github.com",
        image: coverUrl,
        avatar: avatarUrl,
        author: ((_d = data.owner) == null ? void 0 : _d.login) || owner,
        stars: data.stargazers_count !== void 0 ? formatNumberEN(data.stargazers_count) : void 0,
        repo: data.name || repo,
        date,
        indent: 0
      };
      log("GitHub parse: \u6700\u7EC8\u5B57\u6BB5 title=", result.title, "author=", result.author || "\u65E0", "stars=", result.stars || "\u65E0", "date=", result.date || "\u65E0", "repo=", result.repo || "\u65E0");
      return result;
    } catch (e) {
      log("GitHub API fetch error:", e);
      return await this.parseFromHtml();
    }
  }
  async parseFromHtml() {
    var _a;
    try {
      const res = await (0, import_obsidian4.requestUrl)({
        url: this.url,
        headers: {
          "User-Agent": DEFAULT_USER_AGENT,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        }
      });
      if (res.status !== 200)
        return null;
      const parser = new DOMParser();
      const htmlDoc = parser.parseFromString(res.text, "text/html");
      const ogTitle = htmlDoc.querySelector(
        "meta[property='og:title']"
      );
      const title = (ogTitle == null ? void 0 : ogTitle.getAttribute("content")) ? sanitizeText(ogTitle.getAttribute("content") || "") : void 0;
      if (!title)
        return null;
      const ogDesc = htmlDoc.querySelector(
        "meta[property='og:description']"
      );
      const description = (ogDesc == null ? void 0 : ogDesc.getAttribute("content")) ? sanitizeText(ogDesc.getAttribute("content") || "") : void 0;
      const ogImage = htmlDoc.querySelector(
        "meta[property='og:image']"
      );
      const image = (ogImage == null ? void 0 : ogImage.getAttribute("content")) || void 0;
      let stars;
      const starButton = htmlDoc.querySelector(
        "a[href$='/stargazers']"
      );
      if (starButton) {
        const match = (_a = starButton.textContent) == null ? void 0 : _a.match(/[\d,]+/);
        if (match)
          stars = match[0].replace(/,/g, "");
      }
      let date;
      const relativeTime = htmlDoc.querySelector("relative-time");
      if (relativeTime) {
        const datetime = relativeTime.getAttribute("datetime");
        if (datetime) {
          date = formatDateFromString(datetime);
        }
      }
      log("GitHub HTML: \u65E5\u671F\u56DE\u9000\u94FE: datetime(" + ((relativeTime == null ? void 0 : relativeTime.getAttribute("datetime")) || "\u65E0") + ") \u2192 \u6700\u7EC8\u9009\u62E9date=" + (date || "\u65E0"));
      const repoInfo = GitHubParser.extractRepoInfo(this.url);
      const coverUrl = this.useCardImage ? repoInfo ? `https://opengraph.githubassets.com/1/${repoInfo.owner}/${repoInfo.repo}` : image : image || (repoInfo ? `https://avatars.githubusercontent.com/${repoInfo.owner}` : void 0);
      log("GitHub HTML: image=" + (this.useCardImage ? "opengraph" : "avatar") + "(" + (coverUrl || "\u65E0") + ")");
      const result = {
        url: this.url,
        title,
        description,
        host: "github.com",
        image: coverUrl || image,
        author: repoInfo == null ? void 0 : repoInfo.owner,
        stars,
        repo: repoInfo == null ? void 0 : repoInfo.repo,
        date,
        indent: 0
      };
      log("GitHub HTML: \u6700\u7EC8\u5B57\u6BB5 title=", result.title, "author=", result.author || "\u65E0", "stars=", result.stars || "\u65E0", "date=", result.date || "\u65E0");
      return result;
    } catch (e) {
      log("GitHub HTML parse error:", e);
      return null;
    }
  }
};

// src/twitter_parser.ts
var import_obsidian5 = require("obsidian");
var TwitterParser = class {
  constructor(url, proxyUrl) {
    this.url = url;
    this.proxyUrl = proxyUrl;
  }
  static isTwitterUrl(url) {
    const twitterRegex = /^https?:\/\/(www\.)?(x|twitter)\.com\//i;
    return twitterRegex.test(url);
  }
  async parse() {
    var _a, _b, _c;
    try {
      const nitterUrl = new URL(this.proxyUrl);
      const targetUrl = new URL(this.url);
      const fetchUrl = `${nitterUrl.protocol}//${nitterUrl.host}${targetUrl.pathname}${targetUrl.search}`;
      const res = await (0, import_obsidian5.requestUrl)({
        url: fetchUrl,
        headers: {
          "User-Agent": DEFAULT_USER_AGENT,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8"
        }
      });
      if (res.status !== 200)
        return null;
      const htmlDoc = new DOMParser().parseFromString(res.text, "text/html");
      const ogDescription = ((_a = htmlDoc.querySelector("meta[property='og:description']")) == null ? void 0 : _a.getAttribute("content")) || void 0;
      const ogTitle = ((_b = htmlDoc.querySelector("meta[property='og:title']")) == null ? void 0 : _b.getAttribute("content")) || void 0;
      const ogImage = ((_c = htmlDoc.querySelector("meta[property='og:image']")) == null ? void 0 : _c.getAttribute("content")) || void 0;
      const title = ogDescription || void 0;
      const author = ogTitle || void 0;
      let image;
      if (ogImage) {
        image = this.resolveImageUrl(ogImage);
      }
      const views = this.extractViews(htmlDoc);
      const date = this.extractDate(htmlDoc);
      const avatar = this.extractAvatar(htmlDoc);
      log("Twitter parse: title=og:description(" + (ogDescription || "\u65E0") + "), author=og:title(" + (ogTitle || "\u65E0") + "), image=og:image(" + (ogImage || "\u65E0") + "), views=" + (views || "\u65E0") + ", date=" + (date || "\u65E0") + ", avatar=" + (avatar || "\u65E0"));
      if (!title)
        return null;
      const result = {
        url: this.url,
        title,
        host: "x.com",
        image,
        avatar,
        author,
        views,
        date,
        indent: 0
      };
      log("Twitter parse: \u6700\u7EC8\u5B57\u6BB5 title=", result.title, "author=", result.author || "\u65E0", "image=", result.image || "\u65E0", "avatar=", result.avatar || "\u65E0", "views=", result.views || "\u65E0", "date=", result.date || "\u65E0");
      return result;
    } catch (e) {
      log("Twitter parse error:", e);
      return null;
    }
  }
  extractAvatar(doc) {
    const selectors = [
      "img.avatar.round",
      "img.avatar",
      "a.avatar img",
      ".avatar img",
      ".tweet-avatar img",
      "img[src*='avatar']",
      "img[src*='profile_images']"
    ];
    for (const selector of selectors) {
      const img = doc.querySelector(selector);
      const src = img == null ? void 0 : img.getAttribute("src");
      if (src) {
        const resolved = this.resolveImageUrl(src);
        log(`Twitter avatar: \u9009\u62E9\u5668 ${selector} \u5339\u914D\u6210\u529F \u2192 ${resolved}`);
        return resolved;
      }
    }
    const allImgs = doc.querySelectorAll("img[src]");
    for (const img of Array.from(allImgs)) {
      const src = img.getAttribute("src") || "";
      if (src.includes("profile_images") || src.includes("avatar")) {
        const resolved = this.resolveImageUrl(src);
        log(`Twitter avatar: \u5168\u5C40\u626B\u63CF\u5339\u914D \u2192 ${resolved}`);
        return resolved;
      }
    }
    log("Twitter avatar: \u672A\u627E\u5230\u5934\u50CF");
    return void 0;
  }
  extractViews(doc) {
    var _a;
    const tweetStats = doc.querySelectorAll("span.tweet-stat");
    for (const stat of Array.from(tweetStats)) {
      const iconViews = stat.querySelector("span.icon-views");
      if (iconViews) {
        const container = stat.querySelector("div.icon-container");
        if (container) {
          const text = (_a = container.textContent) == null ? void 0 : _a.trim();
          if (text)
            return text;
        }
      }
    }
    return void 0;
  }
  extractDate(doc) {
    var _a;
    const published = doc.querySelector("p.tweet-published");
    if (!published)
      return void 0;
    const text = (_a = published.textContent) == null ? void 0 : _a.trim();
    if (!text)
      return void 0;
    return this.formatDateToUTC8(text);
  }
  formatDateToUTC8(dateStr) {
    const cleaned = dateStr.replace(/\s*·\s*/, " ");
    const date = new Date(cleaned);
    if (isNaN(date.getTime()))
      return void 0;
    const utc8 = new Date(date.getTime() + 8 * 60 * 60 * 1e3);
    const year = utc8.getUTCFullYear();
    const month = String(utc8.getUTCMonth() + 1).padStart(2, "0");
    const day = String(utc8.getUTCDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
  resolveImageUrl(src) {
    if (src.startsWith("//")) {
      return "https:" + src;
    }
    if (src.startsWith("/")) {
      try {
        const proxyBase = new URL(this.proxyUrl);
        return `${proxyBase.protocol}//${proxyBase.host}${src}`;
      } catch (e) {
        return src;
      }
    }
    return src;
  }
};

// src/youtube_parser.ts
var import_obsidian6 = require("obsidian");
var YouTubeParser = class {
  constructor(url, oembedUrl = "https://www.youtube.com/oembed") {
    this.url = url;
    this.oembedUrl = oembedUrl;
  }
  static isYouTubeUrl(url) {
    try {
      const hostname = new URL(url).hostname;
      return hostname === "youtube.com" || hostname === "www.youtube.com" || hostname === "m.youtube.com" || hostname === "youtu.be";
    } catch (e) {
      return false;
    }
  }
  static extractVideoId(url) {
    try {
      const parsed = new URL(url);
      if (parsed.hostname === "youtu.be") {
        return parsed.pathname.slice(1) || null;
      }
      return parsed.searchParams.get("v");
    } catch (e) {
      return null;
    }
  }
  async parse() {
    var _a, _b, _c, _d, _e;
    const videoId = YouTubeParser.extractVideoId(this.url);
    if (!videoId) {
      log("YouTube parse: \u65E0\u6CD5\u63D0\u53D6videoId");
      return null;
    }
    try {
      const cleanUrl = `https://www.youtube.com/watch?v=${videoId}`;
      let title;
      let author;
      let image;
      let avatar;
      let views;
      let date;
      let oembedThumbnail;
      try {
        const oembedUrl = `${this.oembedUrl}?url=${encodeURIComponent(cleanUrl)}&format=json`;
        const res = await (0, import_obsidian6.requestUrl)({
          url: oembedUrl,
          headers: {
            "User-Agent": DEFAULT_USER_AGENT,
            Accept: "application/json"
          }
        });
        if (res.status === 200) {
          const data = res.json;
          title = data.title || void 0;
          author = data.author_name || void 0;
          oembedThumbnail = data.thumbnail_url || void 0;
        }
      } catch (e) {
        log("YouTube oEmbed: \u8BF7\u6C42\u5931\u8D25", e);
      }
      try {
        const htmlRes = await (0, import_obsidian6.requestUrl)({
          url: cleanUrl,
          headers: {
            "User-Agent": DEFAULT_USER_AGENT,
            Accept: "text/html",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8"
          }
        });
        if (htmlRes.status === 200) {
          const htmlText = htmlRes.text;
          const ogImageMatch = htmlText.match(/<meta\s+property="og:image"\s+content="([^"]+)"/);
          if (ogImageMatch) {
            image = ogImageMatch[1];
          }
          const playerMatch = htmlText.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;/);
          if (playerMatch) {
            try {
              const playerData = JSON.parse(playerMatch[1]);
              const viewCount = (_a = playerData == null ? void 0 : playerData.videoDetails) == null ? void 0 : _a.viewCount;
              if (viewCount) {
                views = formatNumberCN(parseInt(viewCount, 10));
              }
              const publishDate = (_c = (_b = playerData == null ? void 0 : playerData.microformat) == null ? void 0 : _b.playerMicroformatRenderer) == null ? void 0 : _c.publishDate;
              if (publishDate) {
                date = formatDateFromString(publishDate);
              }
              if (!title) {
                title = ((_d = playerData == null ? void 0 : playerData.videoDetails) == null ? void 0 : _d.title) || void 0;
              }
              if (!author) {
                author = ((_e = playerData == null ? void 0 : playerData.videoDetails) == null ? void 0 : _e.author) || void 0;
              }
            } catch (e) {
              log("YouTube HTML: \u89E3\u6790ytInitialPlayerResponse\u5931\u8D25", e);
            }
          }
          const dataMatch = htmlText.match(/ytInitialData\s*=\s*(\{.+?\})\s*;/);
          if (dataMatch) {
            try {
              const initData = JSON.parse(dataMatch[1]);
              const avatarUrl = this.extractAvatarFromInitialData(initData);
              if (avatarUrl) {
                avatar = avatarUrl;
              }
            } catch (e) {
              log("YouTube HTML: \u89E3\u6790ytInitialData\u5931\u8D25", e);
            }
          }
          if (!views) {
            const viewsMatch = htmlText.match(/"viewCount"\s*:\s*"(\d+)"/);
            if (viewsMatch) {
              views = formatNumberCN(parseInt(viewsMatch[1], 10));
            }
          }
          if (!date) {
            const dateMatch = htmlText.match(/"publishDate"\s*:\s*"(\d{4}-\d{2}-\d{2})"/);
            if (dateMatch) {
              date = dateMatch[1];
            }
          }
        }
      } catch (e) {
        log("YouTube HTML: \u8BF7\u6C42\u9875\u9762\u5931\u8D25", e);
      }
      if (!image && oembedThumbnail) {
        image = oembedThumbnail;
      }
      if (!image) {
        image = `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
      }
      if (!avatar) {
        const channelMatch = this.url.match(/\/(channel\/[\w-]+)/);
        if (channelMatch) {
          avatar = `https://yt3.ggpht.com/ytc/${channelMatch[1]}=s48-c-k-c0x00ffffff-no-rj`;
        }
      }
      log("YouTube parse: title=", title || "\u65E0", "author=", author || "\u65E0", "image=", image || "\u65E0", "avatar=", avatar || "\u65E0", "views=", views || "\u65E0");
      const result = {
        url: this.url,
        title: title || "YouTube Video",
        host: "youtube.com",
        image,
        avatar,
        author,
        views,
        date,
        indent: 0
      };
      return result;
    } catch (e) {
      log("YouTube parse error:", e);
      return null;
    }
  }
  extractAvatarFromInitialData(initData) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    try {
      const contents = (_d = (_c = (_b = (_a = initData == null ? void 0 : initData.contents) == null ? void 0 : _a.twoColumnWatchNextResults) == null ? void 0 : _b.results) == null ? void 0 : _c.results) == null ? void 0 : _d.contents;
      if (contents) {
        for (const content of contents) {
          const owner = (_f = (_e = content == null ? void 0 : content.videoSecondaryInfoRenderer) == null ? void 0 : _e.owner) == null ? void 0 : _f.videoOwnerRenderer;
          if (((_h = (_g = owner == null ? void 0 : owner.thumbnail) == null ? void 0 : _g.thumbnails) == null ? void 0 : _h.length) > 0) {
            const thumbnails = owner.thumbnail.thumbnails;
            const thumb = thumbnails[thumbnails.length - 1];
            if (thumb == null ? void 0 : thumb.url) {
              return thumb.url;
            }
          }
        }
      }
    } catch (e) {
    }
    return void 0;
  }
};

// src/link_metadata_parser.ts
var LinkMetadataParser = class {
  constructor(url, htmlText, proxyBase) {
    this.url = url;
    this.proxyBase = proxyBase || "";
    const parser = new DOMParser();
    this.htmlDoc = parser.parseFromString(htmlText, "text/html");
  }
  async parse(specialistData) {
    var _a, _b, _c, _d;
    const { hostname } = new URL(this.url);
    let data = {
      url: this.url,
      host: hostname,
      indent: 0
    };
    const allFields = await this.extractAllHtmlFields(
      this.htmlDoc,
      this.proxyBase
    );
    data = { ...data, ...allFields };
    const ogTitle = data["og:title"];
    const twitterTitle = data["twitter:title"];
    const htmlTitle = this.getTitle();
    const specialistTitle = specialistData == null ? void 0 : specialistData.title;
    if (!data.title) {
      data.title = htmlTitle;
    }
    const titleChain = [
      { source: "\u4E13\u7528\u89E3\u6790\u5668title", value: specialistTitle },
      { source: "og:title", value: ogTitle },
      { source: "twitter:title", value: twitterTitle },
      { source: "title", value: htmlTitle }
    ];
    const selectedTitle = resolveFirstDefined(specialistTitle, ogTitle, twitterTitle, htmlTitle);
    if (selectedTitle)
      data.title = selectedTitle;
    log("\u6807\u9898\u56DE\u9000\u94FE:", titleChain.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "), `\u2192 ${selectedTitle || "\u65E0"}`);
    const ogDesc = data["og:description"];
    const twitterDesc = data["twitter:description"];
    const htmlDesc = this.getDescription();
    const specialistDesc = specialistData == null ? void 0 : specialistData.description;
    if (!data.description) {
      data.description = htmlDesc;
    }
    const descChain = [
      { source: "\u4E13\u7528\u89E3\u6790\u5668description", value: specialistDesc },
      { source: "og:description", value: ogDesc },
      { source: "twitter:description", value: twitterDesc },
      { source: "description", value: htmlDesc }
    ];
    const selectedDesc = resolveFirstDefined(specialistDesc, ogDesc, twitterDesc, htmlDesc);
    if (selectedDesc)
      data.description = selectedDesc;
    log("\u7B80\u4ECB\u56DE\u9000\u94FE:", descChain.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "), `\u2192 ${selectedDesc || "\u65E0"}`);
    const specialistImage = specialistData == null ? void 0 : specialistData.image;
    const ogImage = (_a = this.htmlDoc.querySelector(
      "meta[property='og:image']"
    )) == null ? void 0 : _a.getAttribute("content");
    const twitterImage = (_b = this.htmlDoc.querySelector(
      "meta[name='twitter:image'], meta[property='twitter:image']"
    )) == null ? void 0 : _b.getAttribute("content");
    const extractedImages = extractImagesFromDoc(this.htmlDoc);
    const favicon = await this.getFavicon();
    const imageCandidates = [
      { source: "\u4E13\u7528\u89E3\u6790\u5668image", value: specialistImage },
      { source: "og:image", value: ogImage },
      { source: "twitter:image", value: twitterImage },
      { source: "cover", value: extractedImages.cover },
      { source: "avatar", value: extractedImages.avatar },
      { source: "firstImg", value: extractedImages.firstImg },
      { source: "favicon", value: favicon }
    ];
    let selectedImage = "";
    let selectedSource = "";
    for (const candidate of imageCandidates) {
      if (candidate.value) {
        selectedImage = extractCleanImageUrl(candidate.value);
        selectedSource = candidate.source;
        break;
      }
    }
    if (!selectedImage && data.og_image) {
      selectedImage = extractCleanImageUrl(data.og_image);
      selectedSource = "og_image";
    }
    log("\u56FE\u7247\u56DE\u9000\u94FE:", imageCandidates.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "));
    if (selectedImage) {
      data.image = selectedImage;
      log(`\u56FE\u7247\u9009\u62E9: ${selectedSource} \u2192 ${selectedImage}`);
    } else {
      log("\u56FE\u7247\u9009\u62E9: \u65E0\u53EF\u7528\u56FE\u7247");
    }
    if (favicon)
      data.favicon = favicon;
    const specialistAvatar = specialistData == null ? void 0 : specialistData.avatar;
    if (specialistAvatar) {
      data.avatar = specialistAvatar;
    } else if (extractedImages.avatar) {
      data.avatar = extractedImages.avatar;
    } else if (favicon) {
      data.avatar = favicon;
    }
    const specialistDate = specialistData == null ? void 0 : specialistData.date;
    const specialistPubdate = specialistData == null ? void 0 : specialistData.pubdate;
    const dateResult = this.extractDates(this.htmlDoc, data);
    const dateChain = [
      { source: "\u4E13\u7528\u89E3\u6790\u5668date", value: specialistDate },
      { source: "\u4E13\u7528\u89E3\u6790\u5668pubdate", value: specialistPubdate },
      ...dateResult.candidates
    ];
    const finalDate = resolveFirstDefined(specialistDate, specialistPubdate, dateResult.pubdate);
    if (finalDate)
      data.date = finalDate;
    log("\u65E5\u671F\u56DE\u9000\u94FE:", dateChain.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "), `\u2192 ${finalDate || "\u65E0"}`);
    const specialistAuthor = specialistData == null ? void 0 : specialistData.author;
    const metaAuthor = ((_c = this.htmlDoc.querySelector("meta[name='author']")) == null ? void 0 : _c.getAttribute("content")) || void 0;
    const siteNameAuthor = ((_d = this.htmlDoc.querySelector("meta[property='og:site_name']")) == null ? void 0 : _d.getAttribute("content")) || void 0;
    const authorChain = [
      { source: "\u4E13\u7528\u89E3\u6790\u5668author", value: specialistAuthor },
      { source: "meta[author]", value: metaAuthor },
      { source: "og:site_name", value: siteNameAuthor }
    ];
    const finalAuthor = resolveFirstDefined(specialistAuthor, metaAuthor, siteNameAuthor);
    if (finalAuthor)
      data.author = finalAuthor;
    log("\u4F5C\u8005\u56DE\u9000\u94FE:", authorChain.map((c) => `${c.source}(${c.value || "\u65E0"})`).join(" -> "), `\u2192 ${finalAuthor || "\u65E0"}`);
    if (specialistData == null ? void 0 : specialistData.stars)
      data.stars = specialistData.stars;
    if (specialistData == null ? void 0 : specialistData.views)
      data.views = specialistData.views;
    if (specialistData == null ? void 0 : specialistData.duration)
      data.duration = specialistData.duration;
    if (specialistData == null ? void 0 : specialistData.repo)
      data.repo = specialistData.repo;
    if (data.title) {
      data.title = sanitizeText(data.title);
    }
    if (data.description) {
      data.description = sanitizeText(data.description);
    }
    return data.title ? data : null;
  }
  async extractAllHtmlFields(htmlDoc, proxyBase) {
    const result = {};
    const metaTags = htmlDoc.querySelectorAll(
      "meta[property], meta[name]"
    );
    for (const meta of Array.from(metaTags)) {
      const property = meta.getAttribute("property") || meta.getAttribute("name");
      const content = meta.getAttribute("content");
      if (property && content) {
        if ((property.includes("image") || property.includes("video")) && proxyBase) {
          if (content.startsWith("http")) {
            try {
              const contentUrl = new URL(content);
              const proxyUrl = new URL(proxyBase);
              result[property] = `${proxyUrl.protocol}//${proxyUrl.host}${contentUrl.pathname}${contentUrl.search}`;
            } catch (e) {
              result[property] = content;
            }
          } else if (content.startsWith("/")) {
            try {
              const proxyUrl = new URL(proxyBase);
              result[property] = `${proxyUrl.protocol}//${proxyUrl.host}${content}`;
            } catch (e) {
              result[property] = content;
            }
          } else {
            result[property] = content;
          }
        } else {
          result[property] = content;
        }
      }
    }
    const title = htmlDoc.querySelector("title");
    if (title && title.textContent) {
      result["title"] = title.textContent;
    }
    const videoPosters = htmlDoc.querySelectorAll("video[poster]");
    for (let i = 0; i < videoPosters.length; i++) {
      const poster = videoPosters[i].getAttribute("poster");
      if (poster) {
        result[`video_poster_${i}`] = poster;
      }
    }
    const images = htmlDoc.querySelectorAll("img[src]");
    for (let i = 0; i < Math.min(images.length, 5); i++) {
      const src = images[i].getAttribute("src");
      if (src && !src.startsWith("data:")) {
        result[`img_src_${i}`] = src;
      }
    }
    const links = htmlDoc.querySelectorAll(
      "link[rel='icon'], link[rel='shortcut icon'], link[rel='apple-touch-icon']"
    );
    for (const link of Array.from(links)) {
      const rel = link.getAttribute("rel");
      const href = link.getAttribute("href");
      if (rel && href) {
        result[`link_${rel}`] = href;
      }
    }
    return result;
  }
  extractDates(htmlDoc, data) {
    const candidates = [];
    const pubdateCandidates = [
      { source: "article:published_time", selector: "meta[property='article:published_time']" },
      { source: "og:pubdate", selector: "meta[property='og:pubdate']" },
      { source: "pubdate", selector: "meta[name='pubdate']" },
      { source: "datePublished", selector: "meta[itemprop='datePublished']" },
      { source: "date", selector: "meta[name='date']" }
    ];
    const updatedCandidates = [
      { source: "article:modified_time", selector: "meta[property='article:modified_time']" },
      { source: "og:updated_time", selector: "meta[property='og:updated_time']" },
      { source: "dateModified", selector: "meta[itemprop='dateModified']" },
      { source: "lastmod", selector: "meta[name='lastmod']" }
    ];
    let pubdate;
    for (const c of pubdateCandidates) {
      const el = htmlDoc.querySelector(c.selector);
      const value = (el == null ? void 0 : el.getAttribute("content")) || void 0;
      candidates.push({ source: c.source, value });
      if (!pubdate && value) {
        pubdate = formatDateFromString(value);
      }
    }
    if (!pubdate && data.pubdate) {
      candidates.push({ source: "data.pubdate", value: String(data.pubdate) });
      pubdate = formatDateFromString(String(data.pubdate));
    }
    let updated_at;
    for (const c of updatedCandidates) {
      const el = htmlDoc.querySelector(c.selector);
      const value = (el == null ? void 0 : el.getAttribute("content")) || void 0;
      candidates.push({ source: c.source, value });
      if (!updated_at && value) {
        updated_at = formatDateFromString(value);
      }
    }
    if (!updated_at && data.updated_at) {
      candidates.push({ source: "data.updated_at", value: String(data.updated_at) });
      updated_at = formatDateFromString(String(data.updated_at));
    }
    return { pubdate, updated_at, candidates };
  }
  getTitle() {
    const ogTitle = this.htmlDoc.querySelector(
      "meta[property='og:title']"
    );
    if (ogTitle)
      return ogTitle.getAttribute("content") || void 0;
    const title = this.htmlDoc.querySelector("title");
    if (title)
      return title.textContent || void 0;
    return void 0;
  }
  getDescription() {
    const ogDescription = this.htmlDoc.querySelector(
      "meta[property='og:description']"
    );
    if (ogDescription)
      return ogDescription.getAttribute("content") || void 0;
    const metaDescription = this.htmlDoc.querySelector(
      "meta[name='description']"
    );
    if (metaDescription)
      return metaDescription.getAttribute("content") || void 0;
    return void 0;
  }
  async getFavicon() {
    var _a, _b, _c;
    const favicon = (_a = this.htmlDoc.querySelector(
      "link[rel='icon']"
    )) == null ? void 0 : _a.getAttribute("href");
    if (favicon)
      return await this.fixImageUrl(favicon);
    const shortcutIcon = (_b = this.htmlDoc.querySelector(
      "link[rel='shortcut icon']"
    )) == null ? void 0 : _b.getAttribute("href");
    if (shortcutIcon)
      return await this.fixImageUrl(shortcutIcon);
    const appleIcon = (_c = this.htmlDoc.querySelector(
      "link[rel='apple-touch-icon']"
    )) == null ? void 0 : _c.getAttribute("href");
    if (appleIcon)
      return await this.fixImageUrl(appleIcon);
    const { hostname } = new URL(this.url);
    return `https://${hostname}/favicon.ico`;
  }
  async getImage() {
    var _a, _b;
    const ogImage = (_a = this.htmlDoc.querySelector(
      "meta[property='og:image']"
    )) == null ? void 0 : _a.getAttribute("content");
    if (ogImage)
      return await this.fixImageUrl(ogImage);
    const videoPoster = (_b = this.htmlDoc.querySelector(
      "video[poster]"
    )) == null ? void 0 : _b.getAttribute("poster");
    if (videoPoster)
      return await this.fixImageUrl(videoPoster);
    return void 0;
  }
  async fixImageUrl(url) {
    if (url === void 0)
      return "";
    const { hostname } = new URL(this.url);
    let image = url;
    if (url && url.startsWith("//")) {
      const testUrlHttps = `https:${url}`;
      const testUrlHttp = `http:${url}`;
      if (await checkUrlAccessibility(testUrlHttps)) {
        image = testUrlHttps;
      } else if (await checkUrlAccessibility(testUrlHttp)) {
        image = testUrlHttp;
      }
    } else if (url && url.startsWith("/") && this.proxyBase) {
      const base = this.proxyBase.replace(/\/+$/, "");
      image = `${base}${url}`;
    } else if (url && url.startsWith("/") && hostname) {
      const testUrlHttps = `https://${hostname}${url}`;
      const testUrlHttp = `http://${hostname}${url}`;
      const resUrlHttps = await checkUrlAccessibility(testUrlHttps);
      const resUrlHttp = await checkUrlAccessibility(testUrlHttp);
      if (resUrlHttps) {
        image = testUrlHttps;
      } else if (resUrlHttp) {
        image = testUrlHttp;
      }
    } else if (url && url.startsWith("http") && this.proxyBase) {
      try {
        const imageUrl = new URL(url);
        const proxyUrl = new URL(this.proxyBase);
        if (imageUrl.host !== proxyUrl.host) {
          image = `${proxyUrl.protocol}//${proxyUrl.host}${imageUrl.pathname}${imageUrl.search}`;
        }
      } catch (e) {
      }
    }
    return extractCleanImageUrl(image);
  }
};
function checkUrlAccessibility(url) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(true);
    img.onerror = () => resolve(false);
    img.src = url;
  });
}

// src/code_block_generator.ts
var RENDER_FIELDS = [
  "url",
  "title",
  "description",
  "host",
  "image",
  "favicon",
  "avatar",
  "author",
  "date",
  "stars",
  "views",
  "duration",
  "repo"
];
var _CodeBlockGenerator = class {
  constructor(editor) {
    this.editor = editor;
  }
  async convertUrlToCodeBlock(url) {
    const selectedText = this.editor.getSelection();
    const pasteId = this.createBlockHash();
    const fetchingText = `[${t("Fetching data")}#${pasteId}](${url})`;
    this.editor.replaceSelection(fetchingText);
    const linkMetadata = await this.fetchLinkMetadata(url);
    const text = this.editor.getValue();
    const start = text.indexOf(fetchingText);
    if (start < 0) {
      log(`Unable to find text "${fetchingText}" in current editor, bailing out; link ${url}`);
      return;
    }
    const end = start + fetchingText.length;
    const startPos = EditorExtensions.getEditorPositionFromIndex(text, start);
    const endPos = EditorExtensions.getEditorPositionFromIndex(text, end);
    if (!linkMetadata) {
      new import_obsidian7.Notice(t("Failed to fetch"));
      this.editor.replaceRange(selectedText || url, startPos, endPos);
      return;
    }
    this.editor.replaceRange(
      this.genCodeBlock(linkMetadata),
      startPos,
      endPos
    );
  }
  genCodeBlock(linkMetadata) {
    const codeBlockTexts = ["\n```cardlink"];
    const usedFields = [];
    const formatValue = (value) => {
      if (typeof value !== "string")
        return String(value);
      const cleanValue = value.replace(/\r\n|\n|\r/g, " ").replace(/\\/g, "\\\\").trim();
      const escaped = cleanValue.replace(/'/g, "''");
      return `'${escaped}'`;
    };
    for (const fieldName of RENDER_FIELDS) {
      const value = linkMetadata[fieldName];
      if (value !== void 0 && value !== null && value !== "") {
        codeBlockTexts.push(`${fieldName}: ${formatValue(value)}`);
        usedFields.push(fieldName);
      }
    }
    codeBlockTexts.push("```\n");
    log("\u6E32\u67D3\u5361\u7247\u4F7F\u7528\u7684\u5B57\u6BB5:", usedFields.join(", "));
    return codeBlockTexts.join("\n");
  }
  async fetchLinkMetadata(url) {
    var _a, _b, _c, _d;
    if (!url || typeof url !== "string")
      return null;
    if (!url.match(/^https?:\/\//i)) {
      url = "https://" + url;
    }
    logGroupStart(`\u5F00\u59CB\u5206\u6790 ${url}`);
    let parsedUrl;
    try {
      parsedUrl = new URL(url);
    } catch (e) {
      log("URL\u89E3\u6790\u5931\u8D25");
      logGroupEnd();
      return null;
    }
    if (_CodeBlockGenerator.cache) {
      const cached = _CodeBlockGenerator.cache.get(url);
      if (cached) {
        log("\u547D\u4E2D\u7F13\u5B58");
        this.logResult(url, cached);
        logGroupEnd();
        return cached;
      }
    }
    let specialistData = null;
    if (BilibiliParser.isBilibiliUrl(url)) {
      const bilibiliParser = new BilibiliParser(url);
      specialistData = await bilibiliParser.parse();
    }
    if (YouTubeParser.isYouTubeUrl(url)) {
      const youTubeParser = new YouTubeParser(url);
      specialistData = await youTubeParser.parse();
    }
    if (parsedUrl.hostname === "github.com" && GitHubParser.isGitHubUrl(url)) {
      const githubParser = new GitHubParser(url, (_b = (_a = _CodeBlockGenerator.settings) == null ? void 0 : _a.githubCardImage) != null ? _b : true);
      specialistData = await githubParser.parse();
    }
    const isTwitter = TwitterParser.isTwitterUrl(url);
    if (isTwitter) {
      const proxyUrl = ((_c = _CodeBlockGenerator.settings) == null ? void 0 : _c.tpl_x_htmlProxyUrl) || "http://127.0.0.1:8080";
      const twitterParser = new TwitterParser(url, proxyUrl);
      specialistData = await twitterParser.parse();
    }
    if (specialistData && (YouTubeParser.isYouTubeUrl(url) || isTwitter)) {
      this.saveToCache(url, specialistData);
      this.logResult(url, specialistData);
      logGroupEnd();
      return specialistData;
    }
    let fetchUrl = url;
    let proxyBase = "";
    const res = await (() => (0, import_obsidian7.requestUrl)({
      url: fetchUrl,
      headers: {
        "User-Agent": DEFAULT_USER_AGENT,
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8"
      }
    }).catch(() => null))();
    let result = null;
    if (res && res.status === 200) {
      const parser = new LinkMetadataParser(url, res.text, proxyBase);
      result = await parser.parse(specialistData || void 0);
      if (result) {
        this.saveToCache(url, result);
        this.logResult(url, result);
        logGroupEnd();
        return result;
      }
    }
    if (specialistData) {
      this.saveToCache(url, specialistData);
      this.logResult(url, specialistData);
      logGroupEnd();
      return specialistData;
    }
    if ((_d = _CodeBlockGenerator.settings) == null ? void 0 : _d.fallbackApiEnabled) {
      result = await this.fetchFromFallbackApi(url);
      if (result) {
        this.saveToCache(url, result);
        this.logResult(url, result);
        logGroupEnd();
        return result;
      }
    }
    log("\u5206\u6790\u5B8C\u6BD5\uFF1A\u65E0\u7ED3\u679C");
    logGroupEnd();
    return result;
  }
  logResult(url, data) {
    log("\u2500\u2500 \u8F93\u51FA\u5B57\u6BB5 \u2500\u2500");
    for (const key of Object.keys(data)) {
      if (key === "indent")
        continue;
      const value = data[key];
      if (value !== void 0 && value !== null && value !== "") {
        log(`  ${key}: ${value}`);
      }
    }
    log("\u2500\u2500 \u6240\u6709\u539F\u59CB\u5B57\u6BB5 \u2500\u2500");
    for (const [key, value] of Object.entries(data)) {
      log(`  ${key}: ${JSON.stringify(value)}`);
    }
    log("\u5206\u6790\u5B8C\u6BD5 \u2713");
  }
  async fetchFromFallbackApi(url) {
    var _a;
    try {
      const microlinkUrl = `https://api.microlink.io/?url=${encodeURIComponent(url)}`;
      const res = await (0, import_obsidian7.requestUrl)({ url: microlinkUrl });
      if (res.status === 200 && res.json && res.json.status === "success") {
        const data = res.json.data;
        const { hostname } = new URL(url);
        const result = {
          url: data.url || url,
          title: data.title || "",
          description: data.description || "",
          host: hostname,
          indent: 0
        };
        if ((_a = data.image) == null ? void 0 : _a.url) {
          result.image = data.image.url;
        }
        if (result.title) {
          this.saveToCache(url, result);
          return result;
        }
      }
    } catch (e) {
      log("Microlink API fallback error:", e);
    }
    return null;
  }
  saveToCache(url, data) {
    if (_CodeBlockGenerator.cache) {
      _CodeBlockGenerator.cache.set(url, data);
    }
  }
  createBlockHash() {
    let result = "";
    const characters = "abcdefghijklmnopqrstuvwxyz0123456789";
    const charactersLength = characters.length;
    for (let i = 0; i < 4; i++) {
      result += characters.charAt(
        Math.floor(Math.random() * charactersLength)
      );
    }
    return result;
  }
};
var CodeBlockGenerator = _CodeBlockGenerator;
CodeBlockGenerator.settings = null;
CodeBlockGenerator.cache = null;

// src/code_block_processor.ts
var import_obsidian8 = require("obsidian");

// src/errors.ts
var YamlParseError = class extends Error {
};
var NoRequiredParamsError = class extends Error {
};

// src/checkif.ts
var CheckIf = class {
  static isUrl(text) {
    const regex = new RegExp(urlRegex);
    return regex.test(text);
  }
  static isImage(text) {
    const regex = new RegExp(imageRegex);
    return regex.test(text);
  }
  static isLinkedUrl(text) {
    const regex = new RegExp(linkRegex);
    return regex.test(text);
  }
};

// src/icons.ts
var ICON_PLAY = `<svg class="view-icon" style="width:14px;height:14px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect x="2" y="4" width="20" height="16" rx="4" fill="#888"/><path d="M10 8.5v7l5.5-3.5z" fill="white"/></svg>`;
var ICON_STAR = `<svg class="star-icon" style="width:14px;height:14px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>`;
var ICON_DATE = `<svg class="date-icon" style="width:14px;height:14px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><rect x="40" y="40" width="176" height="176" rx="8" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"/><line x1="176" y1="24" x2="176" y2="56" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"/><line x1="80" y1="24" x2="80" y2="56" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"/><line x1="40" y1="88" x2="216" y2="88" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"/></svg>`;

// src/code_block_processor.ts
function insertSvg(container, svgString) {
  const template = document.createElement("template");
  template.innerHTML = svgString.trim();
  const node = template.content.firstChild;
  if (node) {
    container.appendChild(node);
  }
}
function getCardTheme(data) {
  var _a, _b;
  const isTwitter = ((_a = data.host) == null ? void 0 : _a.includes("x.com")) || ((_b = data.host) == null ? void 0 : _b.includes("twitter.com"));
  if (isTwitter) {
    return {
      titleLineClamp: 3,
      titleLineHeight: 1.5,
      showDescription: false
    };
  }
  return {
    titleLineClamp: 2,
    titleLineHeight: 1.4,
    showDescription: true
  };
}
var _CodeBlockProcessor = class {
  constructor(app) {
    this.app = app;
  }
  async run(source, el) {
    try {
      const data = this.parseLinkMetadataFromYaml(source);
      el.appendChild(this.genLinkEl(data));
    } catch (error) {
      if (error instanceof NoRequiredParamsError) {
        el.appendChild(this.genErrorEl(error.message));
      } else if (error instanceof YamlParseError) {
        el.appendChild(this.genErrorEl(error.message));
      } else if (error instanceof TypeError) {
        el.appendChild(this.genErrorEl(t("Internal links error")));
        log(error);
      } else {
        log(t("Cardlink unknown error"), error);
      }
    }
  }
  parseLinkMetadataFromYaml(source) {
    let yaml;
    let indent = -1;
    source = source.split(/\r?\n|\r|\n/g).map(
      (line) => line.replace(/^\t+/g, (tabs) => {
        const n = tabs.length;
        if (indent < 0) {
          indent = n;
        }
        return " ".repeat(n);
      })
    ).join("\n");
    try {
      yaml = (0, import_obsidian8.parseYaml)(source);
    } catch (error) {
      log(error);
      throw new YamlParseError(t("YAML parse error"));
    }
    if (!yaml || !yaml.url || !yaml.title) {
      throw new NoRequiredParamsError(t("Required params missing"));
    }
    const result = {
      url: yaml.url,
      title: yaml.title,
      description: yaml.description,
      host: yaml.host,
      image: yaml.image,
      favicon: yaml.favicon,
      avatar: yaml.avatar,
      author: yaml.author,
      duration: yaml.duration,
      views: yaml.views,
      date: yaml.date || yaml.pubdate,
      stars: yaml.stars,
      repo: yaml.repo,
      indent
    };
    for (const key of Object.keys(yaml)) {
      if (!(key in result)) {
        result[key] = yaml[key];
      }
    }
    return result;
  }
  genErrorEl(errorMsg) {
    const containerEl = document.createElement("div");
    containerEl.addClass("auto-card-link-error-container");
    const spanEl = document.createElement("span");
    spanEl.textContent = `cardlink error: ${errorMsg}`;
    containerEl.appendChild(spanEl);
    return containerEl;
  }
  resolveImageUrl(url) {
    if (!url)
      return "";
    if (url.startsWith("[[") && url.endsWith("]]")) {
      return this.getLocalImagePath(url);
    }
    if (!CheckIf.isUrl(url)) {
      return this.getLocalImagePath(`[[${url}]]`);
    }
    return url;
  }
  genLinkEl(data) {
    var _a, _b, _c;
    const theme = getCardTheme(data);
    const isTwitter = ((_a = data.host) == null ? void 0 : _a.includes("x.com")) || ((_b = data.host) == null ? void 0 : _b.includes("twitter.com"));
    const usedRenderFields = [];
    const containerEl = document.createElement("div");
    containerEl.addClass("auto-card-link-container");
    containerEl.addClass("video-holder");
    if (!((_c = _CodeBlockProcessor.settings) == null ? void 0 : _c.followColorScheme)) {
      containerEl.addClass("no-color-scheme");
    }
    containerEl.setAttr("data-auto-card-link-depth", data.indent);
    const cardEl = document.createElement("a");
    cardEl.setAttr("href", data.url);
    usedRenderFields.push("url");
    cardEl.setAttr("target", "_blank");
    containerEl.appendChild(cardEl);
    if (isTwitter) {
      cardEl.addClass("twitter-card-link");
    }
    const hasImage = !!data.image;
    if (hasImage) {
      usedRenderFields.push("image");
      const coverBox = document.createElement("div");
      coverBox.addClass("cover-box");
      cardEl.appendChild(coverBox);
      const resolvedImage = this.resolveImageUrl(data.image);
      const coverImg = document.createElement("img");
      coverImg.addClass("cover-img");
      coverImg.setAttr("src", resolvedImage);
      coverImg.setAttr("draggable", "false");
      coverImg.onerror = () => {
        coverBox.remove();
      };
      coverBox.appendChild(coverImg);
      if (data.duration) {
        usedRenderFields.push("duration");
        const subtitleEl = document.createElement("div");
        subtitleEl.addClass("video-subtitle");
        const durationEl = document.createElement("span");
        durationEl.addClass("video-duration");
        durationEl.textContent = data.duration;
        subtitleEl.appendChild(durationEl);
        coverBox.appendChild(subtitleEl);
      }
    }
    const contentContainer = document.createElement("div");
    contentContainer.addClass("video-content-container");
    cardEl.appendChild(contentContainer);
    const titleValue = data.repo || data.title || "";
    if (titleValue) {
      if (data.repo)
        usedRenderFields.push("repo");
      else
        usedRenderFields.push("title");
      const titleEl = document.createElement("div");
      titleEl.addClass("video-title");
      titleEl.style.fontSize = "16px";
      titleEl.style.lineHeight = String(theme.titleLineHeight);
      titleEl.style.height = "auto";
      titleEl.style.maxHeight = `${16 * theme.titleLineHeight * theme.titleLineClamp}px`;
      titleEl.style.overflow = "hidden";
      titleEl.style.display = "-webkit-box";
      titleEl.style.webkitLineClamp = String(theme.titleLineClamp);
      titleEl.style.webkitBoxOrient = "vertical";
      titleEl.textContent = titleValue;
      contentContainer.appendChild(titleEl);
    }
    if (theme.showDescription && data.description) {
      usedRenderFields.push("description");
      const descEl = document.createElement("div");
      descEl.addClass("video-description");
      descEl.style.fontSize = "12px";
      descEl.style.lineHeight = "1.4";
      descEl.style.height = "auto";
      descEl.style.maxHeight = "33.6px";
      descEl.style.overflow = "hidden";
      descEl.style.display = "-webkit-box";
      descEl.style.webkitLineClamp = "2";
      descEl.style.webkitBoxOrient = "vertical";
      descEl.textContent = data.description;
      contentContainer.appendChild(descEl);
    }
    const spacer = document.createElement("div");
    spacer.style.flex = "1";
    contentContainer.appendChild(spacer);
    const dataEl = document.createElement("div");
    dataEl.addClass("video-card-info");
    let hasData = false;
    if (data.views) {
      hasData = true;
      usedRenderFields.push("views");
      const viewItem = document.createElement("span");
      viewItem.addClass("cover-info-item");
      insertSvg(viewItem, ICON_PLAY);
      const viewNum = document.createElement("span");
      viewNum.addClass("num-info");
      viewNum.textContent = data.views;
      viewItem.appendChild(viewNum);
      dataEl.appendChild(viewItem);
    }
    if (data.stars) {
      hasData = true;
      usedRenderFields.push("stars");
      const starItem = document.createElement("span");
      starItem.addClass("cover-info-item");
      insertSvg(starItem, ICON_STAR);
      const starCount = document.createElement("span");
      starCount.addClass("num-info");
      starCount.textContent = data.stars;
      starItem.appendChild(starCount);
      dataEl.appendChild(starItem);
    }
    if (data.date) {
      hasData = true;
      usedRenderFields.push("date");
      const dateItem = document.createElement("span");
      dateItem.addClass("cover-info-item");
      insertSvg(dateItem, ICON_DATE);
      const dateText = document.createElement("span");
      dateText.addClass("num-info");
      dateText.textContent = data.date;
      dateItem.appendChild(dateText);
      dataEl.appendChild(dateItem);
    }
    if (hasData) {
      contentContainer.appendChild(dataEl);
    }
    const bottomEl = document.createElement("div");
    bottomEl.addClass("video-card-bottom");
    contentContainer.appendChild(bottomEl);
    const authorEl = document.createElement("div");
    authorEl.addClass("author-info");
    const avatarSrc = data.avatar || data.favicon;
    if (avatarSrc) {
      if (data.avatar)
        usedRenderFields.push("avatar");
      else
        usedRenderFields.push("favicon");
      const img = document.createElement("img");
      img.addClass("avatar-icon");
      img.setAttr("src", avatarSrc);
      img.setAttr("draggable", "false");
      img.onerror = () => {
        img.remove();
      };
      authorEl.appendChild(img);
    }
    if (data.author) {
      usedRenderFields.push("author");
      const authorText = document.createElement("span");
      authorText.addClass("author-name");
      authorText.textContent = data.author;
      authorEl.appendChild(authorText);
    } else if (data.host) {
      usedRenderFields.push("host");
      const hostText = document.createElement("span");
      hostText.addClass("author-name");
      hostText.textContent = data.host;
      authorEl.appendChild(hostText);
    }
    bottomEl.appendChild(authorEl);
    new import_obsidian8.ButtonComponent(containerEl).setClass("auto-card-link-copy-url").setClass("clickable-icon").setIcon("copy").setTooltip(`Copy URL
${data.url}`).onClick(() => {
      navigator.clipboard.writeText(data.url);
      new import_obsidian8.Notice(t("URL copied"));
    });
    log("\u5361\u7247\u6E32\u67D3\u4F7F\u7528\u7684\u5B57\u6BB5:", usedRenderFields.join(", "));
    return containerEl;
  }
  getLocalImagePath(link) {
    var _a;
    link = link.slice(2, -2);
    const imageRelativePath = (_a = this.app.metadataCache.getFirstLinkpathDest(
      (0, import_obsidian8.getLinkpath)(link),
      ""
    )) == null ? void 0 : _a.path;
    if (!imageRelativePath)
      return link;
    return this.app.vault.adapter.getResourcePath(imageRelativePath);
  }
};
var CodeBlockProcessor = _CodeBlockProcessor;
CodeBlockProcessor.settings = null;

// src/cache.ts
var MetadataCache = class {
  constructor(enabled = true, expiryHours = 24) {
    this.cache = /* @__PURE__ */ new Map();
    this.enabled = enabled;
    this.expiryMs = expiryHours * 60 * 60 * 1e3;
  }
  setEnabled(enabled) {
    this.enabled = enabled;
  }
  setExpiry(hours) {
    this.expiryMs = hours * 60 * 60 * 1e3;
  }
  get(url) {
    if (!this.enabled)
      return null;
    const entry = this.cache.get(url);
    if (!entry)
      return null;
    if (Date.now() - entry.timestamp > this.expiryMs) {
      this.cache.delete(url);
      return null;
    }
    return entry.data;
  }
  set(url, data) {
    if (!this.enabled)
      return;
    this.cache.set(url, { data, timestamp: Date.now() });
  }
  clear() {
    this.cache.clear();
  }
  toJSON() {
    const obj = {};
    this.cache.forEach((value, key) => {
      obj[key] = value;
    });
    return obj;
  }
  fromJSON(data) {
    this.cache.clear();
    if (!data)
      return;
    for (const [key, value] of Object.entries(data)) {
      this.cache.set(key, value);
    }
  }
  size() {
    return this.cache.size;
  }
  cleanExpired() {
    let removed = 0;
    const now = Date.now();
    this.cache.forEach((entry, key) => {
      if (now - entry.timestamp > this.expiryMs) {
        this.cache.delete(key);
        removed++;
      }
    });
    return removed;
  }
};

// src/main.ts
var ObsidianAutoCardLink = class extends import_obsidian9.Plugin {
  async onload() {
    await this.loadSettings();
    this.cache = new MetadataCache(
      this.settings.cacheEnabled,
      this.settings.cacheExpiry
    );
    const storedData = await this.loadData();
    const cacheEntries = (storedData == null ? void 0 : storedData["auto-card-link-cache"]) || null;
    this.cache.fromJSON(cacheEntries);
    CodeBlockGenerator.settings = this.settings;
    CodeBlockGenerator.cache = this.cache;
    CodeBlockProcessor.settings = this.settings;
    this.registerMarkdownCodeBlockProcessor("cardlink", async (source, el) => {
      const processor = new CodeBlockProcessor(this.app);
      await processor.run(source, el);
    });
    this.addCommand({
      id: "paste-url-and-enhance",
      name: t("Paste URL and enhance"),
      editorCallback: async (editor) => {
        await this.pasteUrlAndEnhance(editor);
      }
    });
    this.addCommand({
      id: "enhance-selected-url",
      name: t("Render as card"),
      editorCallback: async (editor) => {
        await this.enhanceSelectedUrl(editor);
      }
    });
    if (this.settings.enhanceDefaultPaste) {
      this.registerEvent(
        this.app.workspace.on("editor-paste", (evt) => {
          this.handlePaste(evt);
        })
      );
    }
    if (this.settings.showInMenuItem) {
      this.registerEvent(
        this.app.workspace.on("editor-menu", (menu) => {
          this.addContextMenuItems(menu);
        })
      );
    }
    this.addSettingTab(
      new ObsidianAutoCardLinkSettingTab(this.app, this)
    );
  }
  onunload() {
    void this.saveCacheData();
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    setDebugEnabled(this.settings.debugEnabled);
  }
  async saveSettings() {
    const diff = {};
    for (const key of Object.keys(DEFAULT_SETTINGS)) {
      if (JSON.stringify(this.settings[key]) !== JSON.stringify(DEFAULT_SETTINGS[key])) {
        diff[key] = this.settings[key];
      }
    }
    if (Object.keys(diff).length === 0) {
      try {
        await this.app.vault.adapter.remove(
          `${this.manifest.dir}/data.json`
        );
      } catch (e) {
      }
    } else {
      await this.saveData(diff);
    }
    CodeBlockGenerator.settings = this.settings;
    CodeBlockProcessor.settings = this.settings;
  }
  async saveCacheData() {
    try {
      const cacheData = this.cache.toJSON();
      const cacheStr = JSON.stringify(cacheData);
      if (cacheStr.length < 5e6) {
        const existingData = await this.loadData() || {};
        existingData["auto-card-link-cache"] = cacheData;
        await this.saveData(existingData);
      }
    } catch (e) {
      log("Failed to save cache:", e);
    }
  }
  async pasteUrlAndEnhance(editor) {
    const clipboardText = await navigator.clipboard.readText();
    if (!clipboardText)
      return;
    const url = clipboardText.trim();
    if (!CheckIf.isUrl(url))
      return;
    const generator = new CodeBlockGenerator(editor);
    await generator.convertUrlToCodeBlock(url);
    await this.saveCacheData();
  }
  async enhanceSelectedUrl(editor) {
    const selectedText = editor.getSelection().trim();
    if (!selectedText)
      return;
    let url = selectedText;
    const linkMatch = selectedText.match(/^\[.*?\]\((.*?)\)$/);
    if (linkMatch) {
      url = linkMatch[1];
    }
    if (!CheckIf.isUrl(url))
      return;
    const generator = new CodeBlockGenerator(editor);
    await generator.convertUrlToCodeBlock(url);
    await this.saveCacheData();
  }
  handlePaste(evt) {
    var _a;
    const clipboardText = (_a = evt.clipboardData) == null ? void 0 : _a.getData("text/plain");
    if (!clipboardText)
      return;
    const url = clipboardText.trim();
    if (!CheckIf.isUrl(url))
      return;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian9.MarkdownView);
    if (!activeView)
      return;
    const editor = activeView.editor;
    if (!editor)
      return;
    evt.preventDefault();
    const generator = new CodeBlockGenerator(editor);
    generator.convertUrlToCodeBlock(url).then(async () => {
      await this.saveCacheData();
    });
  }
  addContextMenuItems(menu) {
    menu.addItem((item) => {
      item.setTitle(t("Render as card menu")).setIcon("link").onClick(async () => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian9.MarkdownView);
        if (!activeView)
          return;
        await this.enhanceSelectedUrl(activeView.editor);
      });
    });
  }
};
